name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        run: |
          sleep 5
          docker-compose up -d --build || echo "Deploy failed"