name: CI/CD with Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy
        run: |
          docker-compose down --remove-orphans
          docker-compose up -d --build

      - name: Test Application
        run: |
          sleep 5
          curl -f <http://localhost:80> || exit 1
          curl -f <http://localhost:8000/expenses> || exit 1
